In [25]:
import numpy as np

In [26]:
def Topsis():
    print('请输入参评数目：')
    n = int(input())

    print('请输入指标数目：')
    m = int(input())

    print('请输入类型矩阵：1：极大型 2：极小型 3：中间型 4：区间型')
    kind = input().split(" ")

    print('请输入矩阵：')
    A = np.zeros(shape=(n, m))
    for i in range(n):
        A[i] = input().split(" ")
        A[i] = list(map(float, A[i]))
    print(f'输入的矩阵为：\n{format(A)}')
    return n, m, kind, A

In [27]:
def MinToMax(maxx, x):
    x = list(x)
    ans = [[maxx - e] for e in x]
    return np.array(ans)

In [28]:
def MidToMax(betsx, x):
    x = list(x)
    h = [abs(e - betsx) for e in x]
    M = max(h)
    if M == 0:
        M = 1
    ans = [[1 - e/M] for e in h]
    return np.array(ans)

In [29]:
def RegToMax(lowx, highx, x):
    x = list(x)
    M = max(lowx - min(x), max(x) - highx)
    if M == 0:
        M = 1
    ans = []
    for i in range(len(x)):
        if x[i] < lowx:
            ans.append([(1 - (lowx - x[i]) / M)])
        elif x[i] > highx:
            ans.append([(1 - (x[i] - highx) / M)])
        else:
            ans.append([1])
    return np.array(ans)

In [30]:
n, m, kind, A = Topsis()

请输入参评数目：
请输入指标数目：
请输入类型矩阵：1：极大型 2：极小型 3：中间型 4：区间型
请输入矩阵：
输入的矩阵为：
[[  9.  10. 175. 120.]
 [  8.   7. 164.  80.]
 [  6.   3. 157.  90.]]


In [31]:
X = np.zeros(shape=(n, 1))
for i in range(m):
    if kind[i] == "1":
        v = np.array(A[:, i])
    elif kind[i] == "2":
        maxA = max(A[:, i])
        v = MinToMax(maxA, A[:, i])
    elif kind[i] == "3":
        print('类型三，请输入最优值：')
        bestA = eval(input())
        v = MidToMax(bestA, A[:, i])
    elif kind[i] == "4":
        print('类型四，请输入区间上界a：')
        lowA = eval(input())
        print('类型四，请输入区间下界b：')
        highA = eval(input())
        v = RegToMax(lowA, highA, A[:, i])
    if i == 0:
        X = v.reshape(-1, 1)
    else:
        X = np.hstack((X, v.reshape(-1, 1)))
print(f'统一指标后矩阵为：{format(X)}')

X = X.astype('float')
for j in range(m):
    X[:, j] = X[:, j] / np.sqrt(sum(X[:, j] ** 2))
print(f'标准化矩阵为：\n{format(X)}')

x_max = np.max(X, axis=0)
x_min = np.min(X, axis=0)
d_z = np.sqrt(np.sum(np.square(X - np.tile(x_max, (n, 1))), axis=1))
d_f = np.sqrt(np.sum(np.square(X - np.tile(x_min, (n, 1))), axis=1))
print(f'每个指标的最大值为：{x_max}')
print(f'每个指标的最小值为：{x_min}')
print(f'd+向量：{d_z}')
print(f'd-向量：{d_f}')

s = d_f / (d_z + d_f)
score = 100 * s / sum(s)
for i in range(len(score)):
    print(f'第{i+1}个项目的得分为：{score[i]}')

类型三，请输入最优值：
类型四，请输入区间上界a：
类型四，请输入区间下界b：
统一指标后矩阵为：[[9.  0.  0.  0. ]
 [8.  3.  0.9 0.5]
 [6.  7.  0.2 1. ]]
标准化矩阵为：
[[0.66896473 0.         0.         0.        ]
 [0.59463532 0.3939193  0.97618706 0.4472136 ]
 [0.44597649 0.91914503 0.21693046 0.89442719]]
每个指标的最大值为：[0.66896473 0.91914503 0.97618706 0.89442719]
每个指标的最小值为：[0.44597649 0.         0.         0.        ]
d+向量：[1.61175952 0.69382053 0.79132442]
d-向量：[0.22298824 1.15334862 1.30072534]
第1个项目的得分为：8.886366735657832
第2个项目的得分为：45.653341055701134
第3个项目的得分为：45.46029220864103
