In [1]:
import numpy as np

In [2]:
# A = np.array(eval(input('请输入原始矩阵:')))
A = np.array([[55, 24, 10], [65, 38, 22], [75, 40, 18], [100, 50, 20]])
A

array([[ 55,  24,  10],
       [ 65,  38,  22],
       [ 75,  40,  18],
       [100,  50,  20]])

In [3]:
Mean = np.mean(A, axis=0)
A_norm = A / Mean
print(f'预处理后的矩阵为:\n{A_norm}')

预处理后的矩阵为:
[[0.74576271 0.63157895 0.57142857]
 [0.88135593 1.         1.25714286]
 [1.01694915 1.05263158 1.02857143]
 [1.3559322  1.31578947 1.14285714]]


In [5]:
Y = A_norm[:, 0]

X = A_norm[:, 1:]

absX0_Xi = np.abs(X - np.tile(Y.reshape(-1, 1), (1, X.shape[1])))
absX0_Xi

array([[0.11418376, 0.17433414],
       [0.11864407, 0.37578692],
       [0.03568243, 0.01162228],
       [0.04014273, 0.21307506]])

In [9]:
a = np.min(absX0_Xi)
b = np.max(absX0_Xi)
rho = 0.5
gamma = (a + rho * b) / (absX0_Xi + rho * b)

In [12]:
print(f'子序列中各个指标的灰色关联度分别为:\n{np.mean(gamma, axis=0)}')

子序列中各个指标的灰色关联度分别为:
[0.76966578 0.60058464]
