#### 1、一致性检验

In [9]:
import numpy as np

A = np.array([[1, 2, 3, 5], [1/2, 1, 1/2, 2], [1/3, 2, 1, 2], [1/5, 1/2, 1/2, 1]])

In [10]:
def Consistency_checks(A):
    n = A.shape[0]

    eig_val, eig_vec = np.linalg.eig(A)
    Max_eig = max(eig_val)

    CI = (Max_eig - n) / (n - 1)
    RI = [0, 0.0001, 0.52, 0.89, 1.12, 1.26, 1.36, 1.41, 1.46, 1.49, 1.52, 1.54, 1.56, 1.58, 1.59]

    CR = CI / RI[n-1]

    print(f'一致性指标CI={CI}')
    print(f'一致性比例CR={CR}')

    if CR < 0.1:
        print('该指标为强一致性指标')
    elif CR >= 0.1 and CR < 0.25:
        print('该指标为弱一致性指标')
    else:
        print('该指标为非一致性指标')

    return CR

In [11]:
CR = Consistency_checks(A)
CR

一致性指标CI=(0.037610012730716846+0j)
一致性比例CR=(0.04225844127046837+0j)
该指标为强一致性指标


(0.04225844127046837+0j)

#### 2、算数平均法求权重

In [13]:
def Arithmetic_averaging(A):
    ASum = np.sum(A, axis=0)

    n = A.shape[0]

    Stand_A  = A / ASum

    ASum = np.sum(Stand_A, axis=1)

    weights = ASum  / n

    return weights

In [14]:
weigths = Arithmetic_averaging(A)
weigths

array([0.48885991, 0.18192996, 0.2318927 , 0.09731744])

#### 3、几何平均法求权重

In [15]:
def Geometric_averaging(A):
    A_prod = np.prod(A, axis=1)

    n = A.shape[0]

    A_prod_n = np.power(A_prod, 1/n)

    re_A_prod = A_prod_n / np.sum(A_prod_n)

    return re_A_prod

In [17]:
weigths = Geometric_averaging(A)
weigths

array([0.49492567, 0.17782883, 0.22724501, 0.1000005 ])

#### 4、特征值法求权重

In [18]:
def Eigenvalue_method(A):
    eig_val, eig_vec = np.linalg.eig(A)

    max_index = np.argmax(eig_val)

    max_vec = eig_vec[:, max_index]

    weigths = max_vec / np.sum(max_vec)

    return weigths

In [19]:
weigths = Eigenvalue_method(A)
weigths

array([0.4933895 +0.j, 0.17884562+0.j, 0.230339  +0.j, 0.09742588+0.j])